### ISSUE TITLE
Mysql server has gone away for celery app

### ISSUE THREAD

**Issue by Vuader** [vision1983/nfw#3]
When running the celery worker app, connection to the Mysql server fails after some time of inactivity.

**Comment by vision1983** [comment]
Hi there,

Can you please test with updated version dev 0.0.4.dev3 on git? It should resolve your issue. 

Once a connection is lost or gone and exception is raised it will auto-reconnect / re-initialize.

**Comment by Vuader** [comment]
Thanks, I've applied and will revert back tomorrow. In the mean time, here is there error from this morning:

```
[2017-01-30 12:25:37,407: INFO/MainProcess] Received task: netrino.tasks.confDevice[28f9f626-3074-4741-b3fc-517de46f8785]
[2017-01-30 12:25:37,456: ERROR/PoolWorker-2] Task netrino.tasks.confDevice[28f9f626-3074-4741-b3fc-517de46f8785] raised unexpected: OperationalError(2006, 'MySQL server has gone away')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/dave/code/netrino/netrino/tasks.py", line 43, in confDevice
    result = db.execute(sql, (iptoint(host),))
  File "/home/dave/code/nfw/nfw/mysql.py", line 146, in execute
    result = execute(cursor, query, params)
  File "/home/dave/code/nfw/nfw/mysql.py", line 206, in execute
    cursor.execute(query, params)
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
OperationalError: (2006, 'MySQL server has gone away')
```

**Comment by Vuader** [comment]
confirmed, dev 0.0.4.dev3 resolves this issue
